import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Canvas, useFrame  } from '@react-three/fiber'
import {useRef, useState} from "react";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main Style={"width:1900px; height:738px"}>
        <div Style={"width:100%; height:100%"} >
        <Canvas Style={"width:100%; height:100%"} >
            <Box point={[-3, -2, 0]}/>
            <Box point={[-3, -2, 2]}/>
            <Box point={[1, 0, -1]}/>
            <Box point={[-4, 1.5, 1]}/>
        </Canvas>
        </div>
      </main>
    </>
  )
}

function Box({point}){
    const ref = useRef()
    useFrame((state, delta) => (ref.current.rotation.y += delta * 0.2,ref.current.rotation.x += delta * 0.1))

    return (
        <mesh
            ref={ref}
            position={point}>

            <boxGeometry args={[1, 1, 1]} />
            <meshStandardMaterial />
        </mesh>
    )
}
