import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Canvas, useFrame  } from '@react-three/fiber'
import {useRef, useState} from "react";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <Canvas>
            <Box position={[-1, -1, 0]}/>
        </Canvas>
        </div>
      </main>
    </>
  )
}

function Box({position}){
    const ref = useRef()
    useFrame((state, delta) => (ref.current.rotation.y += delta * 0.2,ref.current.rotation.x += delta * 0.1))

    return (
        <mesh
            ref={ref}
            position>

            <boxGeometry args={[1, 1, 1]} />
            <meshStandardMaterial />
        </mesh>
    )
}
