import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Canvas } from '@react-three/fiber'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <Canvas>
            <mesh>

                <boxGeometry args={[1, 1, 1]} />
                <meshStandardMaterial />
            </mesh>
        </Canvas>
        </div>
      </main>
    </>
  )
}
